name: Captalis API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Step 1 - Check version Newman and Node
        run: |
          cd testes/back-end
          newman --version
          node --version
             
      - name: Step 2 - Install Newman-Reporter-Htmlextra
        run: sudo npm install -g newman-reporter-htmlextra
        
      - name: Step 3 - Execute collection
        run: newman run ./testes/back-end/Captalis-API.postman_collection.json -e ./testes/back-end/api-c317.postman_environment.json --reporters cli,htmlextra --reporter-htmlextra-export ./results/Report.html
   
      - name: Step 4 - Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
            name: report
            path: ./results/Report.html